FROM alpine/git:2.36.2 as download

COPY clone.sh /clone.sh

# RUN . /clone.sh ComfyUI-Manager https://github.com/ltdrdata/ComfyUI-Manager.git 68aa534e1dbe0244eb6c0a0b51824b6c959a2840
# RUN . /clone.sh ComfyUI_IPAdapter_plus https://github.com/cubiq/ComfyUI_IPAdapter_plus.git 9d076a3df0d2763cef5510ec5ab807f6632c39f5
# RUN . /clone.sh comfyui_controlnet_aux https://github.com/Fannovel16/comfyui_controlnet_aux.git 83463c2e4b04e729268e57f638b4212e0da4badc
# RUN . /clone.sh ComfyUI-Custom-Scripts https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git 9f7b3215e6af317603056a9a1666bf6e83e28835
# RUN . /clone.sh ComfyUI-Impact-Pack https://github.com/ltdrdata/ComfyUI-Impact-Pack.git 2708eba825335387de60220d9e461f6e4ab63bc0
# RUN . /clone.sh AIGODLIKE-ComfyUI-Translation https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation.git 10a2e68255cc877abfcbeeb9540c0494b6be1a23
# RUN . /clone.sh ComfyUI-Custom-Scripts https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git 9f7b3215e6af317603056a9a1666bf6e83e28835
# RUN . /clone.sh ComfyUI_LayerStyle_Advance https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git 89aadaa6c0b8c9adfab86f5d0196f1d13383d47c
# RUN . /clone.sh ComfyUI-SUPIR https://github.com/kijai/ComfyUI-SUPIR.git 53fc4f82f139e0875e1f4f3716fbeafa073e4242
# RUN . /clone.sh rgthree-comfy https://github.com/rgthree/rgthree-comfy.git ab37a0bd377a4443d04896b34a9491ddb1cb014b
# RUN . /clone.sh comfyui-mixlab-nodes https://github.com/shadowcz007/comfyui-mixlab-nodes.git 24863e2ed3f058a20227f72df8d1e901e56018f4
# RUN . /clone.sh ComfyUI_InstantID https://github.com/cubiq/ComfyUI_InstantID.git 1ef34ef573581bd9727c1e0ac05aa956b356a510
# RUN . /clone.sh was-node-suite-comfyui https://github.com/WASasquatch/was-node-suite-comfyui.git 9ae952b1b435d2bd846bfe6516919b5a8b9201aa
# RUN . /clone.sh ComfyUI-Easy-Use https://github.com/yolain/ComfyUI-Easy-Use.git 0104f7f6a9ef02ac6651221c4bc2b742c184e79a
# RUN . /clone.sh ComfyUI_Custom_Nodes_AlekPet https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet.git fcf4c2e68e2a035465cb3273cb858a0f31d3bfd8
# RUN . /clone.sh ComfyUI_UltimateSDUpscale https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git 778a475dde8116a2066fe07f6c9ca15554e0b5be
# RUN . /clone.sh ComfyUI-Crystools https://github.com/crystian/ComfyUI-Crystools.git 576b44b9b79e3bf4b5d50457a28924d89a42e7e1
# RUN . /clone.sh ComfyUI-Florence2 https://github.com/kijai/ComfyUI-Florence2.git c9bd1d34eb8689746366d4bb34dfbb195aa8d0e1
# RUN . /clone.sh ComfyUI-KJNodes https://github.com/kijai/ComfyUI-KJNodes.git a5bd3c86c8ed6b83c55c2d0e7a59515b15a0137f
# RUN . /clone.sh ComfyUI-IC-Light https://github.com/kijai/ComfyUI-IC-Light.git 0208191a9bd2a214167c8a52237ecadd1fa0220c
# RUN . /clone.sh comfyui_segment_anything https://github.com/storyicon/comfyui_segment_anything.git ab6395596399d5048639cdab7e44ec9fae857a93
# RUN . /clone.sh comfyui-inpaint-nodes https://github.com/Acly/comfyui-inpaint-nodes.git b9039c22de926919f26b7242cfa4da00d8b6fbec
# RUN . /clone.sh ComfyUI-VideoHelperSuite https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git 5e61bcf218fe3bb7c899bbd584bbc99a9d05fb42
# RUN . /clone.sh sdxl_prompt_styler https://github.com/twri/sdxl_prompt_styler.git 51068179927f79dce14f38c6b1984390ab242be2
# RUN . /clone.sh ComfyUI_Comfyroll_CustomNodes https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes.git d78b780ae43fcf8c6b7c6505e6ffb4584281ceca
# RUN . /clone.sh PuLID_ComfyUI https://github.com/cubiq/PuLID_ComfyUI.git 4e1fd4024cae77a0c53edb8ecc3c8ee04027ebef
# RUN . /clone.sh ComfyUI-WD14-Tagger https://github.com/pythongosssss/ComfyUI-WD14-Tagger.git d33501765c5bf3dca6e90e0ebaa962890999fbc5
RUN . /clone.sh ComfyUI_essentials https://github.com/cubiq/ComfyUI_essentials.git 33ff89fd354d8ec3ab6affb605a79a931b445d99
# RUN . /clone.sh ComfyUI-Advanced-ControlNet https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet.git da254b700db562a22e03358b933c85a9a3392540
# RUN . /clone.sh comfy_mtb https://github.com/melMass/comfy_mtb.git 2441f19db3ef7f7eb1e1073b7d498e2a58bc149c
# RUN . /clone.sh ComfyUI-Inspire-Pack https://github.com/ltdrdata/ComfyUI-Inspire-Pack.git 0a009c149999c335c323e2f7fc03b42865bf454a
# RUN . /clone.sh ComfyUI_FaceAnalysis https://github.com/cubiq/ComfyUI_FaceAnalysis.git 4919e4e931db0edb219ba5086b3c10b8af750631
# RUN . /clone.sh ComfyUI-Allor https://github.com/Nourepide/ComfyUI-Allor.git af9caecc2a4e3d432be6aa8b7826da0bc1bb420c
# RUN . /clone.sh ComfyUI_LayerStyle_Advance https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git 89aadaa6c0b8c9adfab86f5d0196f1d13383d47c
# RUN . /clone.sh ComfyUI-Impact-Subpack https://github.com/ltdrdata/ComfyUI-Impact-Subpack.git 207415285295707316cb5a2a6a9e0bad56dc8f9c
# RUN . /clone.sh ComfyUI-depth-fm https://github.com/kijai/ComfyUI-depth-fm.git 3d73bbe6265e09989e60aafb42a79e289cab6dfd

FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime

ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1

RUN apt-get update && apt-get install -y git curl ffmpeg libsm6 libxext6 build-essential && apt-get clean

ENV ROOT=/stable-diffusion
RUN --mount=type=cache,target=/root/.cache/pip \
  git clone https://github.com/comfyanonymous/ComfyUI.git ${ROOT} && \
  cd ${ROOT} && \
  git checkout master && \
  git reset --hard 9aac21f894a122ddb8d825c57ad61c0db5e630db && \
  pip install -r requirements.txt

RUN mkdir -p /data/.cache/huggingface/hub/ && \
  curl -o /data/.cache/huggingface/hub/cache.tar.gz https://pic.tiusolution.com/cache.tar.gz && \
  tar xvzf /data/.cache/huggingface/hub/cache.tar.gz -C /data/.cache/huggingface/hub && \
  rm /data/.cache/huggingface/hub/cache.tar.gz

COPY --from=download /repositories/ /data/config/comfy/custom_nodes
 
WORKDIR ${ROOT}
COPY . /docker/
RUN chmod u+x /docker/entrypoint.sh && cp /docker/extra_model_paths.yaml ${ROOT}
RUN /docker/init.sh

ENV NVIDIA_VISIBLE_DEVICES=all PYTHONPATH="${PYTHONPATH}:${PWD}" CLI_ARGS=""
EXPOSE 7860
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python -u main.py --listen --port 7860 ${CLI_ARGS}
