#!/usr/bin/env python3

"""Checks and sets default values for config.json before starting the container."""

import json
import re
import os.path
import sys

DEFAULT_FILEPATH = '/data/config/auto/config.json'

DEFAULT_OUTDIRS = {
  "ldsr_steps": 100,
  "ldsr_cached": False,
  "SCUNET_tile": 256,
  "SCUNET_tile_overlap": 8,
  "SWIN_tile": 192,
  "SWIN_tile_overlap": 8,
  "SWIN_torch_compile": False,
  "hypertile_enable_unet": False,
  "hypertile_enable_unet_secondpass": False,
  "hypertile_max_depth_unet": 3,
  "hypertile_max_tile_unet": 256,
  "hypertile_swap_size_unet": 3,
  "hypertile_enable_vae": False,
  "hypertile_max_depth_vae": 3,
  "hypertile_max_tile_vae": 128,
  "hypertile_swap_size_vae": 3,
  "sd_model_checkpoint": "告白 国漫 V3 升级版大模型_V3.safetensors [df500e59c2]",
  "sd_checkpoint_hash": "df500e59c24572cbb697846244a3d80f9066a39a71d26f92c46d80bef226e395",
  "api_display_include_base64_images": False,
  "samples_save": True,
  "samples_format": "png",
  "samples_filename_pattern": "",
  "save_images_add_number": True,
  "save_images_replace_action": "Replace",
  "grid_save": True,
  "grid_format": "png",
  "grid_extended_filename": False,
  "grid_only_if_multiple": True,
  "grid_prevent_empty_spots": False,
  "grid_zip_filename_pattern": "",
  "n_rows": -1,
  "font": "",
  "grid_text_active_color": "#000000",
  "grid_text_inactive_color": "#999999",
  "grid_background_color": "#ffffff",
  "save_images_before_face_restoration": False,
  "save_images_before_highres_fix": False,
  "save_images_before_color_correction": False,
  "save_mask": False,
  "save_mask_composite": False,
  "jpeg_quality": 80,
  "webp_lossless": False,
  "export_for_4chan": True,
  "img_downscale_threshold": 4.0,
  "target_side_length": 4000,
  "img_max_size_mp": 200,
  "use_original_name_batch": True,
  "use_upscaler_name_as_suffix": False,
  "save_selected_only": True,
  "save_init_img": False,
  "temp_dir": "",
  "clean_temp_dir_at_start": False,
  "save_incomplete_images": False,
  "notification_audio": True,
  "notification_volume": 100,
  "outdir_samples": "",
  "outdir_txt2img_samples": "/output/txt2img",
  "outdir_img2img_samples": "/output/img2img",
  "outdir_extras_samples": "/output/extras",
  "outdir_grids": "",
  "outdir_txt2img_grids": "/output/txt2img-grids",
  "outdir_img2img_grids": "/output/img2img-grids",
  "outdir_save": "/output/saved",
  "outdir_init_images": "/output/init-images",
  "save_to_dirs": True,
  "grid_save_to_dirs": True,
  "use_save_to_dirs_for_ui": False,
  "directories_filename_pattern": "[date]",
  "directories_max_prompt_words": 8,
  "ESRGAN_tile": 192,
  "ESRGAN_tile_overlap": 8,
  "realesrgan_enabled_models": [
      "R-ESRGAN 4x+",
      "R-ESRGAN 4x+ Anime6B"
  ],
  "dat_enabled_models": [
      "DAT x2",
      "DAT x3",
      "DAT x4"
  ],
  "DAT_tile": 192,
  "DAT_tile_overlap": 8,
  "set_scale_by_when_changing_upscaler": False,
  "face_restoration": False,
  "face_restoration_model": "CodeFormer",
  "code_former_weight": 0.5,
  "face_restoration_unload": False,
  "auto_launch_browser": "Local",
  "enable_console_prompts": False,
  "show_warnings": False,
  "show_gradio_deprecation_warnings": True,
  "memmon_poll_rate": 8,
  "samples_log_stdout": False,
  "multiple_tqdm": True,
  "enable_upscale_progressbar": True,
  "print_hypernet_extra": False,
  "list_hidden_files": True,
  "disable_mmap_load_safetensors": False,
  "hide_ldm_prints": True,
  "dump_stacks_on_signal": False,
  "unload_models_when_training": False,
  "pin_memory": False,
  "save_optimizer_state": False,
  "save_training_settings_to_txt": True,
  "dataset_filename_word_regex": "",
  "dataset_filename_join_string": " ",
  "training_image_repeats_per_epoch": 1,
  "training_write_csv_every": 500,
  "training_xattention_optimizations": False,
  "training_enable_tensorboard": False,
  "training_tensorboard_save_images": False,
  "training_tensorboard_flush_every": 120,
  "sd_checkpoints_limit": 1,
  "sd_checkpoints_keep_in_cpu": True,
  "sd_checkpoint_cache": 0,
  "sd_unet": "Automatic",
  "enable_quantization": False,
  "emphasis": "Original",
  "enable_batch_seeds": True,
  "comma_padding_backtrack": 20,
  "CLIP_stop_at_last_layers": 1,
  "upcast_attn": False,
  "randn_source": "GPU",
  "tiling": False,
  "hires_fix_refiner_pass": "second pass",
  "sdxl_crop_top": 0,
  "sdxl_crop_left": 0,
  "sdxl_refiner_low_aesthetic_score": 2.5,
  "sdxl_refiner_high_aesthetic_score": 6.0,
  "sd_vae_checkpoint_cache": 0,
  "sd_vae": "Automatic",
  "sd_vae_overrides_per_model_preferences": True,
  "auto_vae_precision_bfloat16": False,
  "auto_vae_precision": True,
  "sd_vae_encode_method": "Full",
  "sd_vae_decode_method": "Full",
  "inpainting_mask_weight": 1.0,
  "initial_noise_multiplier": 1.0,
  "img2img_extra_noise": 0.0,
  "img2img_color_correction": False,
  "img2img_fix_steps": False,
  "img2img_background_color": "#ffffff",
  "img2img_editor_height": 720,
  "img2img_sketch_default_brush_color": "#ffffff",
  "img2img_inpaint_mask_brush_color": "#ffffff",
  "img2img_inpaint_sketch_default_brush_color": "#ffffff",
  "return_mask": False,
  "return_mask_composite": False,
  "img2img_batch_show_results_limit": 32,
  "overlay_inpaint": True,
  "cross_attention_optimization": "Automatic",
  "s_min_uncond": 0.0,
  "token_merging_ratio": 0.0,
  "token_merging_ratio_img2img": 0.0,
  "token_merging_ratio_hr": 0.0,
  "pad_cond_uncond": False,
  "pad_cond_uncond_v0": False,
  "persistent_cond_cache": True,
  "batch_cond_uncond": True,
  "fp8_storage": "Disable",
  "cache_fp16_weight": False,
  "auto_backcompat": True,
  "use_old_emphasis_implementation": False,
  "use_old_karras_scheduler_sigmas": False,
  "no_dpmpp_sde_batch_determinism": False,
  "use_old_hires_fix_width_height": False,
  "dont_fix_second_order_samplers_schedule": False,
  "hires_fix_use_firstpass_conds": False,
  "use_old_scheduling": False,
  "use_downcasted_alpha_bar": False,
  "refiner_switch_by_sample_steps": False,
  "interrogate_keep_models_in_memory": False,
  "interrogate_return_ranks": False,
  "interrogate_clip_num_beams": 1,
  "interrogate_clip_min_length": 24,
  "interrogate_clip_max_length": 48,
  "interrogate_clip_dict_limit": 1500,
  "interrogate_clip_skip_categories": [],
  "interrogate_deepbooru_score_threshold": 0.5,
  "deepbooru_sort_alpha": True,
  "deepbooru_use_spaces": True,
  "deepbooru_escape": True,
  "deepbooru_filter_tags": "",
  "extra_networks_show_hidden_directories": True,
  "extra_networks_dir_button_function": False,
  "extra_networks_hidden_models": "When searched",
  "extra_networks_default_multiplier": 1.0,
  "extra_networks_card_width": 0,
  "extra_networks_card_height": 0,
  "extra_networks_card_text_scale": 1.0,
  "extra_networks_card_show_desc": True,
  "extra_networks_card_description_is_html": False,
  "extra_networks_card_order_field": "Path",
  "extra_networks_card_order": "Ascending",
  "extra_networks_tree_view_style": "Dirs",
  "extra_networks_tree_view_default_enabled": True,
  "extra_networks_tree_view_default_width": 180,
  "extra_networks_add_text_separator": " ",
  "ui_extra_networks_tab_reorder": "",
  "textual_inversion_print_at_load": False,
  "textual_inversion_add_hashes_to_infotext": True,
  "sd_hypernetwork": "None",
  "keyedit_precision_attention": 0.1,
  "keyedit_precision_extra": 0.05,
  "keyedit_delimiters": ".,\\/!?%^*;:{}=`~() ",
  "keyedit_delimiters_whitespace": [
      "Tab",
      "Carriage Return",
      "Line Feed"
  ],
  "keyedit_move": True,
  "disable_token_counters": False,
  "include_styles_into_token_counters": True,
  "return_grid": True,
  "do_not_show_images": False,
  "js_modal_lightbox": True,
  "js_modal_lightbox_initially_zoomed": True,
  "js_modal_lightbox_gamepad": False,
  "js_modal_lightbox_gamepad_repeat": 250,
  "sd_webui_modal_lightbox_icon_opacity": 1,
  "sd_webui_modal_lightbox_toolbar_opacity": 0.9,
  "gallery_height": "",
  "open_dir_button_choice": "Subdirectory",
  "compact_prompt_box": False,
  "samplers_in_dropdown": True,
  "dimensions_and_batch_together": True,
  "sd_checkpoint_dropdown_use_short": False,
  "hires_fix_show_sampler": False,
  "hires_fix_show_prompts": False,
  "txt2img_settings_accordion": False,
  "img2img_settings_accordion": False,
  "interrupt_after_current": True,
  "localization": "zh_CN",
  "quicksettings_list": [
      "sd_model_checkpoint"
  ],
  "ui_tab_order": [],
  "hidden_tabs": [],
  "ui_reorder_list": [],
  "gradio_theme": "Default",
  "gradio_themes_cache": True,
  "show_progress_in_title": True,
  "send_seed": True,
  "send_size": True,
  "enable_reloading_ui_scripts": False,
  "enable_pnginfo": True,
  "save_txt": False,
  "add_model_name_to_info": True,
  "add_model_hash_to_info": True,
  "add_vae_name_to_info": True,
  "add_vae_hash_to_info": True,
  "add_user_name_to_info": False,
  "add_version_to_infotext": True,
  "disable_weights_auto_swap": True,
  "infotext_skip_pasting": [],
  "infotext_styles": "Apply if any",
  "show_progressbar": True,
  "live_previews_enable": True,
  "live_previews_image_format": "png",
  "show_progress_grid": True,
  "show_progress_every_n_steps": -1,
  "show_progress_type": "Approx NN",
  "live_preview_allow_lowvram_full": False,
  "live_preview_content": "Prompt",
  "live_preview_refresh_period": 1000,
  "live_preview_fast_interrupt": False,
  "js_live_preview_in_modal_lightbox": False,
  "hide_samplers": [],
  "eta_ddim": 0.0,
  "eta_ancestral": 1.0,
  "ddim_discretize": "uniform",
  "s_churn": 0.0,
  "s_tmin": 0.0,
  "s_tmax": 0.0,
  "s_noise": 1.0,
  "sigma_min": 0.0,
  "sigma_max": 0.0,
  "rho": 0.0,
  "eta_noise_seed_delta": 0,
  "always_discard_next_to_last_sigma": False,
  "sgm_noise_multiplier": False,
  "uni_pc_variant": "bh1",
  "uni_pc_skip_type": "time_uniform",
  "uni_pc_order": 3,
  "uni_pc_lower_order_final": True,
  "sd_noise_schedule": "Default",
  "postprocessing_enable_in_main_ui": [],
  "postprocessing_disable_in_extras": [],
  "postprocessing_operation_order": [],
  "upscaling_max_images_in_cache": 5,
  "postprocessing_existing_caption_action": "Ignore",
  "disabled_extensions": [
      "lobe-theme"
  ],
  "disable_all_extensions": "none",
  "restore_config_state_file": "",
  "sd_lora": "None",
  "lora_preferred_name": "Alias from file",
  "lora_add_hashes_to_infotext": True,
  "lora_show_all": False,
  "lora_hide_unknown_for_versions": [],
  "lora_in_memory_limit": 0,
  "lora_not_found_warning_console": False,
  "lora_not_found_gradio_warning": False,
  "lora_functional": False,
  "canvas_hotkey_zoom": "Alt",
  "canvas_hotkey_adjust": "Ctrl",
  "canvas_hotkey_shrink_brush": "Q",
  "canvas_hotkey_grow_brush": "W",
  "canvas_hotkey_move": "F",
  "canvas_hotkey_fullscreen": "S",
  "canvas_hotkey_reset": "R",
  "canvas_hotkey_overlap": "O",
  "canvas_show_tooltip": True,
  "canvas_auto_expand": True,
  "canvas_blur_prompt": False,
  "canvas_disabled_functions": [
      "Overlap"
  ],
  "extra_options_txt2img": [],
  "extra_options_img2img": [],
  "extra_options_cols": 1,
  "extra_options_accordion": False,
  "enable_prompt_comments": True,
  "api_enable_requests": True,
  "api_forbid_local_requests": True,
  "api_useragent": "",
  "prioritized_callbacks_app_started": [],
  "prioritized_callbacks_model_loaded": [],
  "prioritized_callbacks_ui_settings": [],
  "prioritized_callbacks_infotext_pasted": [],
  "prioritized_callbacks_script_unloaded": [],
  "prioritized_callbacks_before_ui": [],
  "prioritized_callbacks_list_optimizers": [],
  "prioritized_callbacks_before_token_counter": [],
  "prioritized_callbacks_script_before_process": [],
  "prioritized_callbacks_script_process": [],
  "prioritized_callbacks_script_post_sample": [],
  "prioritized_callbacks_script_on_mask_blend": [],
  "prioritized_callbacks_script_postprocess_maskoverlay": [],
  "control_net_detectedmap_dir": "detected_maps",
  "control_net_models_path": "",
  "control_net_modules_path": "",
  "control_net_unit_count": 3,
  "control_net_model_cache_size": 2,
  "control_net_inpaint_blur_sigma": 7,
  "control_net_no_detectmap": False,
  "control_net_detectmap_autosaving": False,
  "control_net_allow_script_control": False,
  "control_net_sync_field_args": True,
  "controlnet_show_batch_images_in_ui": False,
  "controlnet_increment_seed_during_batch": False,
  "controlnet_disable_openpose_edit": False,
  "controlnet_disable_photopea_edit": False,
  "controlnet_photopea_warning": True,
  "controlnet_ignore_noninpaint_mask": False,
  "controlnet_clip_detector_on_cpu": False,
  "controlnet_control_type_dropdown": False,
  "nudenet_nsfw_censor_label_horizontal_Female_genitalia_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Face_female": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Buttocks_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Female_breast_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Female_genitalia_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Male_breast_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Anus_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Feet_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Belly_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Feet_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Armpits_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Armpits_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Face_male": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Belly_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Male_genitalia_exposed": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Anus_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Female_breast_covered": 1.0,
  "nudenet_nsfw_censor_label_horizontal_Buttocks_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Female_genitalia_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Face_female": 1.0,
  "nudenet_nsfw_censor_label_vertical_Buttocks_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Female_breast_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Female_genitalia_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Male_breast_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Anus_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Feet_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Belly_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Feet_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Armpits_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Armpits_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Face_male": 1.0,
  "nudenet_nsfw_censor_label_vertical_Belly_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Male_genitalia_exposed": 1.0,
  "nudenet_nsfw_censor_label_vertical_Anus_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Female_breast_covered": 1.0,
  "nudenet_nsfw_censor_label_vertical_Buttocks_covered": 1.0,
  "prioritized_callbacks_after_component": [],
  "prioritized_callbacks_on_reload": [],
  "prioritized_callbacks_script_before_process_batch": [],
  "prioritized_callbacks_script_postprocess": [],
  "prioritized_callbacks_script_postprocess_batch": [],
  "prioritized_callbacks_script_postprocess_image_after_composite": [],
  "nudenet_nsfw_censor_enable": True,
  "nudenet_nsfw_censor_save_before_censor": True,
  "nudenet_nsfw_censor_save_mask": False,
  "nudenet_nsfw_censor_gen_filter_type": "Fill color",
  "nudenet_nsfw_censor_live_preview_filter_type": "Fill color",
  "nudenet_nsfw_censor_extras_filter_type": "Variable blur",
  "nudenet_nsfw_censor_mask_shape": "Entire image",
  "nudenet_nsfw_censor_blur_radius": 10,
  "nudenet_nsfw_censor_rectangle_round_radius": 0.5,
  "nudenet_nsfw_censor_mask_blend_radius": 0,
  "nudenet_nsfw_censor_mask_blend_radius_variable_blur": 10,
  "nudenet_nsfw_censor_blur_strength_curve": 3,
  "nudenet_nsfw_censor_pixelation_factor": 5,
  "nudenet_nsfw_censor_fill_color": "#000000",
  "nudenet_nsfw_censor_nms_threshold": 0.5,
  "nudenet_nsfw_censor_verbose_detection": True,
  "nudenet_nsfw_censor_onnx_provider": "CPUExecutionProvider",
  "nudenet_nsfw_censor_selected_labels": [
      "Anus exposed",
      "Female breast exposed",
      "Female genitalia exposed",
      "Male genitalia exposed"
  ],
  "nudenet_nsfw_censor_label_threshold_Anus_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Anus_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Armpits_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Armpits_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Belly_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Belly_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Buttocks_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Buttocks_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Face_female": 0.25,
  "nudenet_nsfw_censor_label_threshold_Face_male": 0.25,
  "nudenet_nsfw_censor_label_threshold_Feet_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Feet_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Female_breast_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Female_breast_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Female_genitalia_covered": 0.25,
  "nudenet_nsfw_censor_label_threshold_Female_genitalia_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Male_breast_exposed": 0.25,
  "nudenet_nsfw_censor_label_threshold_Male_genitalia_exposed": 0.25,
  "nudenet_nsfw_censor_version": "2.0"
}
RE_VALID_OUTDIR = re.compile(r"(^/output(/\.?[\w\-\_]+)+/?$)|(^\s?$)")

DEFAULT_OTHER = {
  "font": "DejaVuSans.ttf",
}

def dict_to_json_file(target_file: str, data: dict):
  """Write dictionary to specified json file"""

  with open(target_file, 'w') as f:
    json.dump(data, f)

def json_file_to_dict(config_file: str) -> dict|None:
   """Load json file into a dictionary. Return None if file does not exist."""

   if os.path.isfile(config_file):
    with open(config_file, 'r') as f:
      return json.load(f)
   else:
      return None

def replace_if_invalid(value: str, replacement: str, pattern: str|re.Pattern[str]) -> str:
  """Returns original value if valid, fallback value if invalid"""

  if re.match(pattern, value):
    return value
  else:
    return replacement

def check_and_replace_config(config_file: str, target_file: str = None):
  """Checks given file for invalid values. Replaces those with fallback values (default: overwrites file)."""

  # Get current user config, or empty if file does not exists
  data = json_file_to_dict(config_file) or {}

  # Check and fix output directories
  for k, def_val in DEFAULT_OUTDIRS.items():
    if k not in data:
      data[k] = def_val
    else:
      data[k] = replace_if_invalid(value=data[k], replacement=def_val, pattern=RE_VALID_OUTDIR)

  # Check and fix other default settings
  for k, def_val in DEFAULT_OTHER.items():
    if k not in data:
      data[k] = def_val

  # Write results to file
  dict_to_json_file(target_file or config_file, data)

if __name__ == '__main__':
  if len(sys.argv) > 1:
    check_and_replace_config(*sys.argv[1:])
  else:
    check_and_replace_config(DEFAULT_FILEPATH)

