name: Build Images

on:
  push:
    branches: feat/hxr
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          # - comfy
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

      - name: login to docker registry
        run: docker login -u ${{ ALIYUN_DOCKER_PASSWORD }} -p ${{ ALIYUN_DOCKER_USER_NAME }} registry.cn-shanghai.aliyuncs.com

      - name: Build docker image
        run: docker compose --profile ${{ matrix.profile }} build --progress plain

      - name: Push docker image
        run: |
          IMAGE_NAME="registry.cn-shanghai.aliyuncs.com/jcjy-docker/sd-webui"
          docker tag webui-docker-${{ matrix.profile }} $IMAGE_NAME:test
          docker push $IMAGE_NAME:test
