name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          # - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

      - name: login to docker registry
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} iyjian-docker.pkg.coding.net

      - name: Build docker image
        run: docker compose --profile ${{ matrix.profile }} build --progress plain

      - name: Push docker image
        run: |
          IMAGE_NAME="iyjian-docker.pkg.coding.net/jcjy/docker/webui-docker-${{ matrix.profile }}"
          docker tag webui-docker-${{ matrix.profile }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
