name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          # - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: docker tag sd-auto:78 iyjian-docker.pkg.coding.net/sd-auto:78
      - run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: docker push iyjian-docker.pkg.coding.net/sd-auto:78    
